[env:jc3248w535]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 115200

board_build.arduino.memory_type = qio_opi
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L

build_flags =
    -Iinclude
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_MODE=1
    -DLV_CONF_INCLUDE_SIMPLE

lib_deps =
    moononournation/GFX Library for Arduino@^1.4.9
    lvgl/lvgl@^9.2.2
    https://github.com/me-processware/JC3248W535-Driver.git

board_upload.flash_size = 16MB
board_build.partitions = partitions.csv
